version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=llm_rag_db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

volumes:
  postgres_data: